//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        public int id { get; set; }
        public int ProductID { get; set; }
        public int PointOfSaleID { get; set; }
        public System.DateTime shelfLife { get; set; }
    
        public virtual MedicalPreparations MedicalPreparations { get; set; }
        public virtual PointsOfSale PointsOfSale { get; set; }
    }
}
